### ISSUE TITLE
failed to import docs

### ISSUE THREAD

**Issue by zhanghaiyang1** [iris-contrib/swagger#10]
Can't import docs, can someone help me
![docs](https://user-images.githubusercontent.com/12377710/102314220-0cb4ce00-3fad-11eb-8358-710c9d751fda.png)

**Comment by kataras** [comment]
Hello, try `  _ "github.com/your_username/your_project/docs"`

**Comment by zhanghaiyang1** [comment]
it's works，use go mod's module name, like this    _ "xxx/docs"
